#define CEM_BOOBS 01
#define CEM_CAPE 02
#define CEM_WINGS 03
#define CEM_ELF_EARS 04
#define CEM_ELF_EARS_ROTATED 05

#define BODY_FALLBACK 1911

#define FIRST_PERSON_RIGHT_HAND 1912
#define FIRST_PERSON_RIGHT_HAND_OVERLAY 1913
#define FIRST_PERSON_RIGHT_HAND_SLIM 1914
#define FIRST_PERSON_RIGHT_HAND_SLIM_OVERLAY 1915


#define FIRST_PERSON_LEFT_HAND 1916
#define FIRST_PERSON_LEFT_HAND_OVERLAY 1917
#define FIRST_PERSON_LEFT_HAND_SLIM 1918
#define FIRST_PERSON_LEFT_HAND_SLIM_OVERLAY 1919

#define LEFT_ARM_SLIM 202
#define RIGHT_ARM_SLIM 203